#**Load in numpy (remember to pip install numpy first)**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np



#**The Basics**

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get dimension
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
# Get shape
print("The shape of a is : ", a.shape)
print("The shape of b is : ", b.shape)


The shape of a is :  (3,)
The shape of b is :  (2, 3)


In [ ]:
!apt-get install -y git


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.


In [ ]:
!git config --global user.email "owaisahmad014@gmail.com"
!git config --global user.name "Owais Ahmad"


In [ ]:
!git clone https://github.com/owaisahmad315/NumPy.git


Cloning into 'NumPy'...


In [1]:
!pwd


/content


In [17]:
!git remote -v

origin	https://owaisahmad315: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@github.com/owaisahmad315/Artificial-Intelligence-Basic-Practice.git (fetch)
origin	https://owaisahmad315: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@github.com/owaisahmad315/Artificial-Intelligence-Basic-Practice.git (push)


In [19]:
! git add .

In [20]:
! git status

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   Lecture_27.ipynb
	new file:   Lecture_34.ipynb
	new file:   Lecture_35.ipynb
	new file:   NumPy.ipynb
	new file:   Untitled



In [ ]:
! f