#**Load in numpy (remember to pip install numpy first)**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np



#**The Basics**

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get dimension
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
# Get shape
print("The shape of a is : ", a.shape)
print("The shape of b is : ", b.shape)


The shape of a is :  (3,)
The shape of b is :  (2, 3)


In [ ]:
!git clone https://github.com/owaisahmad315/NumPy.git


Cloning into 'NumPy'...


In [19]:
! git add .

In [20]:
! git status

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   Lecture_27.ipynb
	new file:   Lecture_34.ipynb
	new file:   Lecture_35.ipynb
	new file:   NumPy.ipynb
	new file:   Untitled



In [23]:
! git commit -a -m "firstt commit"

[master 229fd5c] firstt commit
 5 files changed, 5 insertions(+), 1 deletion(-)
 rewrite Lecture_27.ipynb (98%)
 create mode 100644 Lecture_34.ipynb
 create mode 100644 Lecture_35.ipynb
 create mode 100644 NumPy.ipynb
 create mode 100644 Untitled


In [25]:
username = input("username")

usernameowaisahmad315


In [26]:
from getpass import getpass
password = getpass("enter password")

enter password··········


In [64]:
!git commit -m "Remove unwanted files"


[main 6c432d0] Remove unwanted files
 5 files changed, 5 deletions(-)
 delete mode 100644 Lecture_23.ipynb
 delete mode 100644 Lecture_25.ipynb
 delete mode 100644 Lecture_27.ipynb
 delete mode 100644 Lecture_34.ipynb
 delete mode 100644 Lecture_35.ipynb


In [65]:
!git push origin main


/usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret store: 1: /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret: not found
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 236 bytes | 78.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/owaisahmad315/NumPy.git
   c490a0d..6c432d0  main -> main
